# Generated by Django 6.0.1 on 2026-02-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
                ('posicion', models.CharField(choices=[('DEL', 'Delantero'), ('MED', 'Mediocampista'), ('DEF', 'Defensa'), ('POR', 'Portero')], default='MED', max_length=3)),
                ('estrellas', models.IntegerField(default=1)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
