# Generated by Django 6.0.2 on 2026-02-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesionado',
            name='posicion',
            field=models.CharField(choices=[('DEL', 'Delantero'), ('MED', 'Mediocampista'), ('DEF', 'Defensa'), ('POR', 'Portero'), ('NA', 'Sin especificar')], default='NA', max_length=3),
        ),
        migrations.CreateModel(
            name='DesignacionArbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=120)),
                ('equipo_visitante', models.CharField(max_length=120)),
                ('arbitro_nombre', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('equipo_local', 'equipo_visitante')},
            },
        ),
    ]
