# Generated by Django 6.0.2 on 2026-02-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_designacion_arbitro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
                ('motivo', models.CharField(blank=True, max_length=150)),
                ('jornada', models.CharField(blank=True, max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['equipo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='lesionado',
            name='retorno_esperado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lesionado',
            name='tipo_lesion',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
